### ISSUE TITLE
Run CounterFit in docker container

### ISSUE THREAD

**Issue by buzzsurfr** [CounterFit-IoT/CounterFit#13]
Before writing a PR to make CounterFit work in docker--is there any reason _NOT_ to do so? It looks like all of the emulation happens through the socket through the CounterFit library.

I've already patched a container to work as well--I'm now testing with some of the sensors and actuators to make sure it doesn't inhibit functionality.

I also recognize that it's fairly easy to get started with CounterFit and you'd need the same packages installed whether or not it runs in docker. My specific use case is that I setup a number of virtualenvs and want to simplify the process by orchestrating a container (one line and simpler install vs two lines + installation).

**Comment by jimbobbennett** [comment]
Apologies - I missed this.

Go for it! There's no reason not to have docker as an alternative to installing the Python application. As long as we support both, for those folks who don't use docker.

**Comment by jimbobbennett** [comment]
Docker container created!

```sh
docker pull jimbobbennett/counterfit:latest
```

When you run this, you need to map port 5000 to a port on your localhost.

More details and the docker file is here: https://github.com/CounterFit-IoT/counterfit-docker-container
