### ISSUE TITLE
Update `lxml` to 4.6.4 or higher (missing wheels for Python 3.10)

### ISSUE THREAD

**Issue by karmek-k** [CounterFit-IoT/CounterFit#16]
Hi!

I came here from the Microsoft IoT course.
I wanted to use a virtual device, but installing CounterFit fails with the following error:

```
*********************************************************************************
Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
*********************************************************************************
```

- OS: Windows 10
- Python version: 3.10.4

Before that I had a missing Visual Studio build tools error, I downloaded them, but now the error above occurs.

After some research I found out that `lxml==4.6.3` tries to install `lxml` from source - https://github.com/streamlink/streamlink/issues/4100#issuecomment-945180777
The same issue discussion also says that `lxml==4.6.4` fixes this problem - https://github.com/streamlink/streamlink/issues/4100#issuecomment-958599725

Could you please update `lxml` in `setup.py`, so that it's possible to install CounterFit without compiling `lxml` from source?

Thanks in advance 😄

**Comment by jimbobbennett** [comment]
Done!
