### ISSUE TITLE
Running Error In Windows 10

### ISSUE THREAD

**Issue by joykangangi** [CounterFit-IoT/CounterFit#20]
Hi, 
I'm using python 3.10.7 and I've installed `counterfit`, `counterfit-connection` and `counterfit-shims-grove` on a virtual environment. But on running `counterfit` on the terminal I get the error `AttributeError: module 'dns.rdtypes' has no attribute 'ANY'`. How can I solve this?

**Comment by Ricky2333** [comment]
Same question. I met the this problem with My Mac (with Apple Silicon & python 3.9.10)😭

**Comment by ThomsenTop** [comment]
I had the same issue, so i read a couple of places, and what worked for me was to do this:
pip install dnspython==2.2.1
